In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

import keras
from keras.models import Sequential     
from keras.layers import Dense 
from keras.utils import np_utils            


SyntaxError: invalid syntax (number.py, line 398)

In [26]:
from numpy import genfromtxt
FILENAME = 'data/dataset_simplified.csv' 
DELIMITER = ';'

data = genfromtxt(FILENAME, delimiter=DELIMITER)
data[0, 0] = 0

In [27]:
print(f'ndim: {np.ndim(data)}')
print(f'shape: {np.shape(data)}')
print(f'size: {np.size(data)}')

print(data[0:5])
print('...')
print(data[-5:])

# day, time_decimal, king_percent, wickham_percent

ndim: 2
shape: (5007, 4)
size: 20028
[[0.   0.   0.83 0.93]
 [3.   0.1  0.83 0.93]
 [3.   0.2  0.83 0.93]
 [3.   0.3  0.83 0.93]
 [3.   0.4  0.83 0.93]]
...
[[ 2.   20.6   0.48  0.9 ]
 [ 2.   20.7   0.49  0.91]
 [ 2.   20.8   0.5   0.91]
 [ 2.   20.9   0.54  0.91]
 [ 2.   21.    0.55  0.91]]


In [ ]:
# King George Square
# Wickham Terrace Car Parks

# Wilson Parking
# First Parking
# AM60
# Secure Parking - 21 Martin Street

In [30]:
data_king = data.copy()
data_king = np.delete(data_king, 3, 1)

data_wickham = data.copy()
data_wickham = np.delete(data_wickham, 2, 1)
